// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace PoorMansTsqlFormatterVSPackage2022
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidPoorMansTSqlFormatterSSMSVSPackagePkgString = "5e84b709-1e60-4116-a702-4cdb1a282d6e";
        public static Guid guidPoorMansTSqlFormatterSSMSVSPackagePkg = new Guid(guidPoorMansTSqlFormatterSSMSVSPackagePkgString);

        public const string guidPoorMansTSqlFormatterSSMSVSPackageCmdSetString = "201bf73c-de53-48a2-a912-c3b8308dacce";
        public static Guid guidPoorMansTSqlFormatterSSMSVSPackageCmdSet = new Guid(guidPoorMansTSqlFormatterSSMSVSPackageCmdSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int cmdidPoorMansFormatSQL = 0x0100;
        public const int cmdidPoorMansSqlOptions = 0x0101;
    }
}