// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace PoorMansTsqlFormatterVSPackage2022
{
    internal sealed partial class Vsix
    {
        public const string Id = "PoorMansTsqlFormatterVSPackage2022.1195479c-aac2-42d8-8d65-93e9fdaac533";
        public const string Name = "Poor Man's T-Sql Formatter VS Extension 2022";
        public const string Description = @"A simple free (AGPL) T-SQL Formatting Extension for Visual Studio 2022. Based on the work by Tao Klerk's up until VS 2019. Modified by Will Robertson under AGPL-3.0 License";
        public const string Language = "en-US";
        public const string Version = "22.0";
        public const string Author = "TaoKlerks";
        public const string Tags = "";
    }
}
